[package]
name = "omaha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hard-xml = "1.15.0"
uuid = "1.2"
ct-codecs = "1"
