[package]
name = "update-format-crau"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2 = "0.4.4"
log = "0.4.19"
protobuf = "3"
rsa = { version = "0.9.10", features = ["sha2"] }
